import './styles/globals.scss';
import type { Metadata } from 'next';
import { Noto_Sans_KR, Roboto } from 'next/font/google';
import React from 'react';

const notoSansKr = Noto_Sans_KR({
  subsets: ['latin'],
  weight: ['100', '400', '700', '900'],
});

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['100', '400', '700'],
  variable: '--roboto',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${notoSansKr.className} ${roboto.className} scrollbar-hide`}>
        {children}
      </body>
    </html>
  );
}
